# Generated by Django 5.1.1 on 2025-04-15 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ccname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'company_category',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tblemployee',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cmpname', models.CharField(max_length=100)),
                ('noofvacancies', models.IntegerField()),
                ('requiredqualification', models.CharField(max_length=100)),
                ('requiredexperience', models.CharField(max_length=100)),
                ('jobdescription', models.CharField(max_length=3000)),
                ('jobtype', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('internship', 'Internship')], default='full-time', max_length=100)),
                ('applystartdate', models.DateField()),
                ('lastdate', models.DateField()),
                ('skillsrequired', models.CharField(max_length=100)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.city')),
            ],
            options={
                'db_table': 'job',
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('strmobileno', models.CharField(max_length=10)),
                ('strstatus', models.CharField(max_length=100)),
                ('profile', models.ImageField(null=True, upload_to='profile/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.city')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applydate', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.job')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.member')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='MemberEducation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passingyear', models.CharField(max_length=4)),
                ('institute', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.member')),
            ],
            options={
                'db_table': 'membereducation',
            },
        ),
        migrations.CreateModel(
            name='MemberExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organizationname', models.CharField(max_length=100)),
                ('worktitle', models.CharField(max_length=100)),
                ('workdetails', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('totalmonthexperience', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.member')),
            ],
            options={
                'db_table': 'memberexperience',
            },
        ),
        migrations.CreateModel(
            name='MemberLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.member')),
            ],
            options={
                'db_table': 'memberlanguage',
            },
        ),
        migrations.CreateModel(
            name='MemberLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link_name', models.CharField(max_length=100)),
                ('link_url', models.URLField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.member')),
            ],
            options={
                'db_table': 'memberlink',
            },
        ),
        migrations.CreateModel(
            name='MemberSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.member')),
            ],
            options={
                'db_table': 'memberskills',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=100)),
                ('msgdt', models.DateField()),
                ('fromlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
                ('tologin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cmpname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('strmobileno', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('strstatus', models.CharField(max_length=100)),
                ('cmp_strength', models.IntegerField(blank=True, null=True)),
                ('ccid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.companycategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.city')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.state')),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.organization'),
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overview', models.TextField(max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('positionname', models.CharField(max_length=100)),
                ('companycategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.companycategory')),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.positions'),
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.positions'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posttitle', models.CharField(max_length=100)),
                ('postcontent', models.ImageField(upload_to='content/')),
                ('postdesc', models.CharField(max_length=100, null=True)),
                ('postdttime', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.post')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commentsdate', models.DateField(auto_now_add=True)),
                ('comments', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.post')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.state'),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.member')),
            ],
        ),
    ]
