# Generated by Django 5.1.1 on 2025-04-16 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_member_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ccid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.companycategory'),
        ),
    ]
