# Generated by Django 5.1.1 on 2025-04-16 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.agency'),
        ),
    ]
