# Generated by Django 5.1.1 on 2025-04-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.organization'),
        ),
    ]
