# Generated by Django 5.1.1 on 2025-04-16 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_job_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.agency'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.organization'),
        ),
    ]
